---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Find files that are older than 90 days
      find: 
        path: /tmp/*
        file_type: file
        age: 90
        age_stamp: dtime
        recursive: yes
      register: found 
    - name: Zip found files that are older than 90 days
      archive: 
        path: "{{found.files|map(attribute='path')|list}}"
        format: zip
        dest: "/tmp/file{{ansible_date_time.date}}.over90days.zip"
