---
- hosts: all
  become: yes
  become_method: sudo
  tasks: 
    - name: Install vim
      package:
        name: vim
        state: present
    - name: Install tree on CentOS
      yum:
        name: tree
        state: present
      when: ansible_distribution == "CentOS"
    - name: Install tree on Ubuntu and Debian
      apt:
        name: tree
        state: present
      when: ansible_distribution == "Ubuntu" and ansible_distribution == "Debian"
    

      