---
- name: Install Apache WebServer
  hosts: all
  become: yes
  become_method: sudo
  tasks: 
    - name: install apache
      apt:
        name: apache2
        state: present
      when: ansible_distribution == "Ubuntu"
