---
- name: searche for users that are not active for 90 days and disables them, backup of their home director
  hosts: all
  tasks:
    - shell: lastlog -b 90 -u 1000- | awk '! /Never logged in/ {if (NR!=1) {print $1}}' | while read user; do chage -E0 $user; tar -czf /home/$user.tar.gz /home/$user; done
